/* Everything you can do to one class, plus the shared sheets (notifications,
   profile, sharing). Views call these; nothing here knows which view it is in. */

import { state } from '../core/store.js';
import { findBooking } from '../core/store.js';
import { cancelBooking } from '../core/store.js';
import { restoreBooking } from '../core/store.js';
import { startExtend } from '../core/store.js';
import { extendBy } from '../core/store.js';
import { stopExtend } from '../core/store.js';
import { saveAttendance } from '../core/store.js';
import { markAllNotificationsRead } from '../core/store.js';
import { logout } from '../core/store.js';
import { isStudent } from '../core/store.js';
import { now } from '../core/clock.js';
import { nowHHMM } from '../core/util.js';
import { at } from '../core/util.js';
import { subjectColor } from '../core/data.js';
import { ATT_STATUSES } from '../core/data.js';
import { SUBJECT_ROSTERS } from '../core/data.js';
import { computeStatus } from '../core/domain.js';
import { statusLabel } from '../core/domain.js';
import { rosterFor } from '../core/domain.js';
import { rosterForBooking } from '../core/domain.js';
import { attendanceFor } from '../core/domain.js';
import { streakFor } from '../core/domain.js';
import { starsFrom } from '../core/domain.js';
import { html } from '../ui/dom.js';
import { on } from '../ui/dom.js';
import { setHTML } from '../ui/dom.js';
import { icon } from '../ui/icons.js';
import { subjectBadge } from '../ui/icons.js';
import { toast } from '../ui/toast.js';
import { openSheet } from '../ui/sheet.js';
import { confirmDialog } from '../ui/sheet.js';
import { navigate } from '../ui/router.js';
import { dayLabel } from '../ui/format.js';
import { dateLong } from '../ui/format.js';
import { durationText } from '../ui/format.js';
import { minutesText } from '../ui/format.js';
import { timeAgo } from '../ui/format.js';
import { personName } from '../ui/format.js';
import { openBookingSheet } from './booking.js';
import { googleCalendarUrl } from '../features/share.js';
import { whatsappText } from '../features/share.js';
import { whatsappUrl } from '../features/share.js';
import { icsFor } from '../features/share.js';
import { saveFile } from '../features/host.js';
import { copyText } from '../features/host.js';
import { onClaude } from '../features/host.js';
import { toggleTheme } from '../fx/theme.js';
import { getTheme } from '../fx/theme.js';

export function statusPill(st) { return html`<span class="pill st-${st}">${st === 'ongoing' || st === 'extending' ? html`<i class="pulse"></i>` : ''}${statusLabel(st)}</span>`; }

/* ======================================================================
   Class sheet
   ====================================================================== */
export function openClassSheet(id) {
  const b0 = findBooking(id);
  if (!b0) { toast('Kelas ini tidak dijumpai lagi.', 'error'); return; }
  const s = openSheet({ title: b0.subject, cls: 'sheet-class', keepFocus: true, icon: subjectBadge(b0.subject, 'md', 'is-solid') });
  s.el.style.setProperty('--c', subjectColor(b0.subject));
  function render() {
    const b = findBooking(id);
    if (!b) { s.close(); return; }
    const n = now();
    const st = computeStatus(b, n);
    const u = state.user;
    const live = st === 'ongoing' || st === 'extending';
    const roster = rosterFor(b.subject);
    const att = b.attendance || {};
    const present = roster.filter(x => att[x] === 'hadir' || att[x] === 'lewat').length;
    const onTime = roster.filter(x => att[x] === 'hadir').length;
    const mine = u && att[u.name];
    const author = (b.autoGenerated || b.createdBy === 'JADUAL TETAP') ? '' : b.createdBy;
    const leftMin = Math.max(0, Math.round((at(b.date, b.to) - n) / 60000));
    const startsMin = Math.round((at(b.date, b.from) - n) / 60000);
    s.setContent(html`
      <div class="cs-top">
        ${statusPill(st)}
        ${b.autoGenerated ? html`<span class="pill">${icon('tetap', 13)} Jadual tetap</span>` : ''}
      </div>
      <div class="cs-when">
        <div class="cs-time">${b.from}<span>–</span>${b.to}</div>
        <div class="cs-date">${dateLong(b.date)} · ${durationText(b.from, b.to)}</div>
        ${live ? html`<div class="cs-live">${st === 'extending' ? 'Sedang extend' : minutesText(leftMin) + ' lagi'}</div>` : st === 'upcoming' && startsMin < 24 * 60 ? html`<div class="cs-soon">Bermula ${startsMin < 60 ? 'dalam ' + startsMin + ' minit' : 'dalam ' + minutesText(startsMin)}</div>` : ''}
      </div>
      <dl class="cs-facts">
        <div><dt>Guru</dt><dd>${b.teacher}</dd></div>
        ${b.notes ? html`<div><dt>Catatan</dt><dd>${b.notes}</dd></div>` : ''}
        ${author ? html`<div><dt>${b.recorded ? 'Direkod oleh' : 'Ditempah oleh'}</dt><dd>${personName(author)}${b.updatedBy ? html`<span class="muted"> · dikemaskini oleh ${personName(b.updatedBy)}</span>` : ''}</dd></div>` : ''}
        ${(b.extensionHistory || []).length ? html`<div><dt>Extend</dt><dd>${b.extensionHistory.map(x => html`<span class="ext-chip">${x.fixed ? '+' + x.fixed + ' min' : 'hingga ' + (x.extendedUntil || 'dihentikan')}</span>`)}<span class="muted"> · asal tamat ${b.originalTo || b.to}</span></dd></div>` : ''}
        ${st !== 'upcoming' && Object.keys(att).length ? html`<div><dt>Kehadiran</dt><dd><b>${present}/${roster.length}</b> hadir<span class="muted"> · ${onTime} bintang skibidi</span>${mine ? html`<span class="att-me t-${mine}">Anda: ${mine === 'tidak' ? 'tidak hadir' : mine}${mine === 'hadir' ? ', +1 bintang skibidi' : mine === 'lewat' ? ', tiada bintang' : ''}</span>` : ''}</dd></div>` : ''}
        ${SUBJECT_ROSTERS[b.subject] ? html`<div><dt>Senarai</dt><dd>${roster.length} pelajar (${b.subject} sahaja)</dd></div>` : ''}
      </dl>
      <div class="cs-actions">
        ${live && u ? (st === 'extending'
          ? html`<button type="button" class="btn danger" data-a="stopext">${icon('clock', 18)}<span>Hentikan extend</span></button>`
          : html`<button type="button" class="btn ghost" data-a="extend">${icon('clock', 18)}<span>Extend kelas</span></button>`) : ''}
        ${(live || (st === 'upcoming' && startsMin < 120)) ? html`<button type="button" class="btn ghost" data-a="display">${icon('display', 18)}<span>Paparan kelas</span></button>` : ''}
        ${state.isAdmin && st !== 'cancelled' ? html`<button type="button" class="btn ghost" data-a="att">${icon('check', 18)}<span>Kehadiran</span></button>` : ''}
        ${u && st !== 'cancelled' && st !== 'ended' ? html`<button type="button" class="btn ghost" data-a="edit">${icon('kelas', 18)}<span>Edit</span></button>` : ''}
        ${u && st === 'upcoming' ? html`<button type="button" class="btn ghost danger-text" data-a="cancel">${icon('trash', 18)}<span>Batal</span></button>` : ''}
        ${u && st === 'cancelled' && state.isAdmin ? html`<button type="button" class="btn ghost" data-a="restore">${icon('undo', 18)}<span>Pulihkan</span></button>` : ''}
      </div>
      ${st === 'upcoming' ? html`<div class="cs-share">
        <a class="link-btn" href="${googleCalendarUrl(b)}" target="_blank" rel="noopener">${icon('calplus', 16)} Google Calendar</a>
        <a class="link-btn" href="${whatsappUrl(whatsappText([b], 'Kelas tambahan 5 Sigma', n))}" target="_blank" rel="noopener">${icon('whatsapp', 16)} Kongsi WhatsApp</a>
        ${onClaude ? '' : html`<button type="button" class="link-btn" data-a="ics">${icon('download', 16)} Fail .ics</button>`}
      </div>` : ''}`);
  }
  render();
  const unsubscribeTimer = setInterval(render, 30000);
  const prevClose = s.close;
  s.close = v => { clearInterval(unsubscribeTimer); prevClose(v); };
  on(s.body, 'click', '[data-a]', async (e, el) => {
    const a = el.dataset.a;
    const b = findBooking(id);
    if (!b) return;
    if (a === 'extend') { s.close(); openExtendSheet(id); }
    else if (a === 'stopext') { s.close(); openStopExtendSheet(id); }
    else if (a === 'display') { s.close(); navigate('paparan'); }
    else if (a === 'att') { s.close(); openAttendanceSheet(id); }
    else if (a === 'edit') { s.close(); openBookingSheet({ editId: id }); }
    else if (a === 'cancel') { s.close(); startCancel(id); }
    else if (a === 'restore') { const r = await restoreBooking(id); toast(r.ok ? 'Kelas dipulihkan' : r.message, r.ok ? 'success' : 'error'); render(); }
    else if (a === 'ics') { const r = await saveFile('kelas-' + b.subject.toLowerCase().replace(/\s+/g, '-') + '-' + b.date + '.ics', icsFor([b]), 'text/calendar'); if (!r.ok) toast(r.message, 'error'); }
  });
  return s;
}

/* ======================================================================
   Cancel with undo
   ====================================================================== */
export async function startCancel(id, opts) {
  const b = findBooking(id);
  if (!b) return;
  const ok = await confirmDialog({ title: 'Batalkan ' + b.subject + '?', message: dayLabel(b.date, now()) + ', ' + b.from + '–' + b.to + ' bersama ' + b.teacher + '. Rakan sekelas akan dimaklumkan.', confirmLabel: 'Ya, batalkan', cancelLabel: 'Kekalkan', tone: 'danger' });
  if (!ok) return;
  const res = await cancelBooking(id, opts);
  if (!res.ok) { toast(res.message, 'error'); return; }
  toast(b.subject + ' dibatalkan', { type: 'warning', action: { label: 'Buat asal', run: async () => { const r = await restoreBooking(id); toast(r.ok ? 'Pembatalan diundur' : r.message, r.ok ? 'success' : 'error'); } } });
}

/* ======================================================================
   Extend
   ====================================================================== */
export function openExtendSheet(id) {
  const b = findBooking(id);
  if (!b) return;
  const s = openSheet({ title: 'Extend ' + b.subject, sub: 'Kelas kini tamat ' + b.to + '. Pilih tempoh tambahan, atau extend sehingga anda hentikan.', cls: 'is-dialog', keepFocus: true,
    content: html`<div class="ext-grid">${[15, 30, 45, 60].map(m => html`<button type="button" class="choice" data-m="${m}"><b>+${m} min</b><span>hingga ${addMin(b.to, m)}</span></button>`)}</div>
      <button type="button" class="btn ghost btn-block" data-open>${icon('clock', 16)} Extend tanpa had (hentikan kemudian)</button>
      <p class="form-error" role="alert" hidden></p>` });
  const err = s.body.querySelector('.form-error');
  on(s.body, 'click', '[data-m]', async (e, el) => {
    el.disabled = true;
    const r = await extendBy(id, +el.dataset.m);
    el.disabled = false;
    if (!r.ok) { err.textContent = r.message; err.hidden = false; return; }
    s.close(); toast(b.subject + ' dilanjutkan hingga ' + r.to, 'success');
  });
  s.body.querySelector('[data-open]').addEventListener('click', async () => {
    const r = await startExtend(id);
    if (!r.ok) { err.textContent = r.message; err.hidden = false; return; }
    s.close(); toast('Kelas ' + b.subject + ' sedang di-extend', 'success');
  });
}
function addMin(t, m) { const [h, mm] = t.split(':').map(Number); const v = Math.min(h * 60 + mm + m, 1439); return String(Math.floor(v / 60)).padStart(2, '0') + ':' + String(v % 60).padStart(2, '0'); }

export function openStopExtendSheet(id) {
  const b = findBooking(id);
  if (!b) return;
  const s = openSheet({ title: 'Hentikan extend', sub: 'Masukkan waktu ' + b.subject + ' sebenarnya tamat.', cls: 'is-dialog', keepFocus: true,
    content: html`<form class="dialog-form"><label class="field"><span class="field-label">Tamat pada</span><input id="stopext-time" class="input" type="time" value="${nowHHMM(now())}"></label>
      <p class="form-error" role="alert" hidden></p>
      <div class="sheet-actions"><button type="button" class="btn ghost" data-x>Batal</button><button type="submit" class="btn primary">Hentikan</button></div></form>` });
  const err = s.body.querySelector('.form-error');
  s.body.querySelector('[data-x]').addEventListener('click', () => s.close());
  s.body.querySelector('form').addEventListener('submit', async e => {
    e.preventDefault();
    const r = await stopExtend(id, s.body.querySelector('input').value);
    if (!r.ok) { err.textContent = r.message; err.hidden = false; return; }
    s.close(); toast('Extend dihentikan', 'info');
  });
}

/* ======================================================================
   Attendance (admin)
   ====================================================================== */
export function openAttendanceSheet(id) {
  const b = findBooking(id);
  if (!b || !state.isAdmin) return;
  const draft = Object.assign({}, b.attendance || {});
  const roster = rosterForBooking(b);
  const s = openSheet({ title: 'Kehadiran ' + b.subject, sub: dateLong(b.date) + ', ' + b.from + '–' + b.to, wide: false, cls: 'sheet-att', keepFocus: true, icon: subjectBadge(b.subject, 'md') });
  function render() {
    const counts = { hadir: 0, lewat: 0, dikecualikan: 0, tidak: 0 };
    roster.forEach(nm => { if (draft[nm]) counts[draft[nm]]++; });
    const marked = roster.filter(nm => draft[nm]).length;
    s.setContent(html`
      <div class="att-head">
        <div class="att-tally">${ATT_STATUSES.map(x => html`<span class="tally t-${x.id}"><i></i>${x.label} <b>${counts[x.id]}</b></span>`)}</div>
        <button type="button" class="btn ghost sm" data-all>${icon('check', 15)} Semua hadir</button>
      </div>
      <p class="muted att-note">${marked}/${roster.length} ditanda${SUBJECT_ROSTERS[b.subject] ? ' · senarai khas ' + b.subject : ''}. Tekan sekali lagi untuk kosongkan.</p>
      <p class="att-rule">${icon('star', 14)}<span><b>Hadir</b> (tepat masa) dapat 1 bintang skibidi. <b>Lewat</b> tidak dapat bintang.</span></p>
      <div class="att-list">${roster.map(nm => {
        return html`<div class="att-row"><span class="att-name">${personName(nm)}${draft[nm] === 'hadir' ? html`<small class="att-star">${icon('star', 12)} bintang skibidi</small>` : ''}</span>
          <span class="seg" role="group" aria-label="Status ${nm}">${ATT_STATUSES.map(x => html`<button type="button" class="${draft[nm] === x.id ? 'is-on t-' + x.id : ''}" data-who="${nm}" data-v="${x.id}" title="${x.label}" aria-pressed="${draft[nm] === x.id ? 'true' : 'false'}">${x.short}</button>`)}</span></div>`;
      })}</div>
      <p class="form-error" role="alert" hidden></p>
      <div class="sheet-actions"><button type="button" class="btn ghost" data-x>Tutup</button><button type="button" class="btn primary" data-save>Simpan kehadiran</button></div>`);
  }
  render();
  on(s.body, 'click', '[data-who]', (e, el) => {
    const nm = el.dataset.who, v = el.dataset.v;
    if (draft[nm] === v) delete draft[nm]; else draft[nm] = v;
    const y = s.body.querySelector('.att-list').scrollTop; render(); s.body.querySelector('.att-list').scrollTop = y;
  });
  on(s.body, 'click', '[data-all]', () => { roster.forEach(nm => { if (!draft[nm]) draft[nm] = 'hadir'; }); render(); });
  on(s.body, 'click', '[data-x]', () => s.close());
  on(s.body, 'click', '[data-save]', async (e, el) => {
    el.disabled = true;
    const r = await saveAttendance(id, draft);
    el.disabled = false;
    if (!r.ok) { const er = s.body.querySelector('.form-error'); er.textContent = r.message; er.hidden = false; return; }
    s.close(); toast('Kehadiran disimpan', 'success');
  });
}

/* ======================================================================
   Notifications
   ====================================================================== */
const NOTIF_IC = { BOOKING_CREATED: 'tempah', CLASS_STARTED: 'clock', EXTENSION_STARTED: 'clock', EXTENSION_STOPPED: 'clock', BOOKING_UPDATED: 'kelas', BOOKING_CANCELLED: 'trash' };
export function openNotifications() {
  const s = openSheet({ title: 'Notifikasi', cls: 'sheet-notif', keepFocus: true });
  function render() {
    const list = state.notifications;
    const unread = list.filter(x => !x.read).length;
    const canDevice = !onClaude && 'Notification' in window && Notification.permission === 'default';
    s.setContent(html`
      <div class="notif-tools"><span class="muted">${unread ? unread + ' belum dibaca' : 'Semua sudah dibaca'}</span>
        ${unread ? html`<button type="button" class="btn ghost sm" data-mark>${icon('check', 15)} Tandakan semua dibaca</button>` : ''}</div>
      ${canDevice ? html`<button type="button" class="banner-btn" data-enable>${icon('bell', 16)} Terima notifikasi pada peranti ini juga</button>` : ''}
      <div class="notif-list">${list.length ? list.map(x => html`<div class="notif${x.read ? '' : ' is-unread'}"><span class="notif-ic t-${(x.type || '').toLowerCase()}">${icon(NOTIF_IC[x.type] || 'bell', 16)}</span>
        <div><b>${x.title}</b>${x.body ? html`<p>${x.body}</p>` : ''}<time>${timeAgo(x.createdAt, Date.now())}</time></div></div>`) : html`<div class="empty"><b>Tiada notifikasi lagi</b><p>Tempahan baharu, perubahan dan kelas yang bermula akan muncul di sini.</p></div>`}</div>`);
  }
  render();
  on(s.body, 'click', '[data-mark]', async () => { const r = await markAllNotificationsRead(); if (r.ok) toast(r.count + ' notifikasi ditanda dibaca', 'success'); setTimeout(render, 60); });
  on(s.body, 'click', '[data-enable]', async () => { try { const p = await Notification.requestPermission(); toast(p === 'granted' ? 'Notifikasi peranti diaktifkan' : 'Notifikasi peranti tidak dibenarkan', p === 'granted' ? 'success' : 'info'); } catch (e) { /* ignore */ } render(); });
  return s;
}

/* ======================================================================
   Profile
   ====================================================================== */
export function openProfile() {
  const u = state.user;
  if (!u) return;
  const rec = state.users[u.name];
  const n = now();
  const student = isStudent();
  const a = student ? attendanceFor(state.bookings, u.name) : null;
  const s = openSheet({ title: personName(u.name), sub: (state.isAdmin ? 'Pelajar · Admin' : u.type) + (rec && rec.lastLoginAt ? ' · log masuk ' + timeAgo(rec.lastLoginAt.getTime(), n.getTime()) : ''), cls: 'is-dialog sheet-profile', keepFocus: true,
    content: html`
      ${student && a && a.total ? html`<div class="prof-stats"><div><b>${a.rate}%</b><span>kehadiran</span></div><div><b>${starsFrom(a.counts)}</b><span>bintang skibidi</span></div><div><b>${streakFor(state.bookings, u.name, n)}</b><span>streak tepat masa</span></div></div>` : ''}
      <div class="menu-list">
        <button type="button" data-a="theme">${icon(getTheme() === 'dark' ? 'sun' : 'moon', 18)}<span>${getTheme() === 'dark' ? 'Tema subuh (cerah)' : 'Tema malam (gelap)'}</span></button>
        <button type="button" data-a="notif">${icon('bell', 18)}<span>Notifikasi</span></button>
        <button type="button" data-a="display">${icon('display', 18)}<span>Paparan kelas</span></button>
        <button type="button" data-a="tetapan">${icon('tetapan', 18)}<span>Tetapan</span></button>
        <button type="button" data-a="logout" class="danger-text">${icon('logout', 18)}<span>Log keluar</span></button>
      </div>` });
  on(s.body, 'click', '[data-a]', (e, el) => {
    const a2 = el.dataset.a;
    if (a2 === 'theme') { s.close(); setTimeout(() => toggleTheme(el), 210); }
    else if (a2 === 'notif') { s.close(); openNotifications(); }
    else if (a2 === 'display') { s.close(); navigate('paparan'); }
    else if (a2 === 'tetapan') { s.close(); navigate('tetapan'); }
    else if (a2 === 'logout') { s.close(); logout(); }
  });
}

/* ======================================================================
   Share a set of classes (a week, a filter)
   ====================================================================== */
export function openShareSheet(list, title) {
  const n = now();
  const text = whatsappText(list, title, n);
  const s = openSheet({ title: 'Kongsi jadual', sub: list.length + ' kelas · ' + title, cls: 'sheet-share', keepFocus: true,
    content: html`<pre class="share-preview">${text}</pre>
      <div class="share-actions">
        <a class="btn primary" href="${whatsappUrl(text)}" target="_blank" rel="noopener">${icon('whatsapp', 18)}<span>Hantar ke WhatsApp</span></a>
        <button type="button" class="btn ghost" data-copy>${icon('list', 18)}<span>Salin teks</span></button>
        ${onClaude ? '' : html`<button type="button" class="btn ghost" data-ics>${icon('calplus', 18)}<span>Fail kalendar (.ics)</span></button>`}
      </div>` });
  on(s.body, 'click', '[data-copy]', async () => { toast(await copyText(text) ? 'Jadual disalin. Tampal dalam kumpulan kelas.' : 'Tidak dapat menyalin. Pilih teks dan salin secara manual.', 'success'); });
  on(s.body, 'click', '[data-ics]', async () => { const r = await saveFile('jadual-5sigma.ics', icsFor(list), 'text/calendar'); if (!r.ok) toast(r.message, 'error'); });
}

export function liveBookings() {
  const n = now();
  return state.bookings.filter(b => { const st = computeStatus(b, n); return st === 'ongoing' || st === 'extending'; });
}
