/* Admin pages and settings.
   - Edit Kelas (admin): add a class that was missed (any date, then mark
     attendance), change or cancel any class quietly (no notification),
     restore a cancelled one, mark attendance.
   - Jadual Tetap (admin): weekly repeating classes on a week board.
   - Tetapan (everyone, as in the original): look and motion, subject teachers,
     teacher genders, workshop teachers, the data source (real or demo) and the clock. */

import { state } from '../core/store.js';
import { restoreBooking } from '../core/store.js';
import { addTemplate } from '../core/store.js';
import { removeTemplate } from '../core/store.js';
import { setSubjectTeacher } from '../core/store.js';
import { setTeacherGender } from '../core/store.js';
import { addWorkshopTeacher } from '../core/store.js';
import { removeWorkshopTeacher } from '../core/store.js';
import { resetDemo } from '../core/store.js';
import { exportBackup } from '../core/store.js';
import { importBackup } from '../core/store.js';
import { refreshNow } from '../core/store.js';
import { dataInfo } from '../core/store.js';
import { setDataSource } from '../core/store.js';
import { now } from '../core/clock.js';
import { getOffset } from '../core/clock.js';
import { setOffset } from '../core/clock.js';
import { isoDate } from '../core/util.js';
import { at } from '../core/util.js';
import { pad2 } from '../core/util.js';
import { normalize } from '../core/util.js';
import { toMinutes } from '../core/util.js';
import { SUBJECTS } from '../core/data.js';
import { WEEK_ORDER } from '../core/data.js';
import { DAY_MY } from '../core/data.js';
import { APP_VERSION } from '../core/data.js';
import { subjectColor } from '../core/data.js';
import { computeStatus } from '../core/domain.js';
import { sortByTime } from '../core/domain.js';
import { allKnownTeachers } from '../core/domain.js';
import { defaultTeacherFor } from '../core/domain.js';
import { isMarked } from '../core/domain.js';
import { html } from '../ui/dom.js';
import { setHTML } from '../ui/dom.js';
import { on } from '../ui/dom.js';
import { icon } from '../ui/icons.js';
import { subjectBadge } from '../ui/icons.js';
import { subjectIcon } from '../ui/icons.js';
import { toast } from '../ui/toast.js';
import { openSheet } from '../ui/sheet.js';
import { confirmDialog } from '../ui/sheet.js';
import { promptDialog } from '../ui/sheet.js';
import { dayLabel } from '../ui/format.js';
import { dateLong } from '../ui/format.js';
import { dateShort } from '../ui/format.js';
import { durationText } from '../ui/format.js';
import { statusPill } from './actions.js';
import { startCancel } from './actions.js';
import { openClassSheet } from './actions.js';
import { openAttendanceSheet } from './actions.js';
import { openBookingSheet } from './booking.js';
import { saveFile } from '../features/host.js';
import { onClaude } from '../features/host.js';
import { getTheme } from '../fx/theme.js';
import { setTheme } from '../fx/theme.js';
import { motionReduced } from '../fx/motion.js';
import { setReducedMotion } from '../fx/motion.js';

/* ================================================================ Edit Kelas */
let kq = '', kf = 'semua', kn = 30;
const KF = [['semua', 'Semua'], ['akan', 'Akan datang'], ['selesai', 'Selesai'], ['batal', 'Dibatalkan']];

function kelasPaint(el) {
  const n = now();
  const q = normalize(kq.trim());
  const all = sortByTime(state.bookings).reverse();
  const list = all.filter(b => {
    const st = computeStatus(b, n);
    if (kf === 'akan' && st !== 'upcoming') return false;
    if (kf === 'selesai' && st !== 'ended') return false;
    if (kf === 'batal' && st !== 'cancelled') return false;
    return !q || normalize([b.subject, b.teacher, b.date, b.date.split('-').reverse().join('/'), b.notes || ''].join(' ')).includes(q);
  });
  const body = el.querySelector('[data-klist]');
  setHTML(body, list.length ? html`<div class="adm-list">${list.slice(0, kn).map(b => {
    const st = computeStatus(b, n);
    return html`<div class="adm-row st-${st}" style="--c:${subjectColor(b.subject)}">${subjectBadge(b.subject, 'md')}
      <button type="button" class="adm-main" data-open="${b.id}"><b>${b.subject}</b><span>${b.teacher}${b.autoGenerated ? ' · jadual tetap' : ''}${b.recorded ? ' · direkod admin' : ''}</span></button>
      <span class="adm-when"><b>${dayLabel(b.date, n)}</b><span>${b.from}–${b.to} · ${durationText(b.from, b.to)}</span></span>
      ${statusPill(st)}
      <span class="adm-acts">
        ${st === 'cancelled' ? html`<button type="button" class="btn ghost sm" data-restore="${b.id}">${icon('undo', 15)}<span>Pulihkan</span></button>` : html`
          <button type="button" class="btn ghost sm" data-edit="${b.id}">${icon('kelas', 15)}<span>Edit</span></button>
          ${st !== 'upcoming' ? html`<button type="button" class="btn ghost sm" data-att="${b.id}">${icon('check', 15)}<span>${isMarked(b) ? 'Kehadiran' : 'Tanda'}</span></button>` : ''}
          <button type="button" class="btn ghost sm danger-text" data-kcancel="${b.id}">${icon('trash', 15)}<span>Batal</span></button>`}
      </span></div>`;
  })}</div>${list.length > kn ? html`<div class="more-row"><button type="button" class="btn ghost" data-kmore>Tunjuk ${Math.min(30, list.length - kn)} lagi</button></div>` : ''}`
    : html`<div class="empty"><b>Tiada kelas dijumpai</b><p>${q ? 'Cuba kata kunci lain.' : 'Belum ada kelas dalam kategori ini.'}</p></div>`);
  el.querySelectorAll('[data-kf]').forEach(c => c.classList.toggle('is-on', c.dataset.kf === kf));
  const cnt = el.querySelector('[data-kcount]');
  if (cnt) cnt.textContent = list.length + ' kelas';
}

export const kelasView = {
  id: 'kelas',
  render(el) {
    setHTML(el, html`
      <div class="page-head"><div><h2 class="page-title">Edit kelas</h2><p class="page-sub">Tambah, ubah atau batalkan mana-mana kelas, termasuk kelas yang terlupa dimasukkan. Perubahan dari halaman ini tidak menghantar notifikasi kepada kelas.</p></div>
        <div class="page-tools"><span class="pill gold">${icon('key', 13)} Admin</span><button type="button" class="btn primary" data-kadd>${icon('plus', 18)}<span>Tambah kelas</span></button></div></div>
      <div class="adm-tools">
        <label class="search-box">${icon('search', 16)}<input class="input" type="search" placeholder="Cari subjek, guru atau tarikh" aria-label="Cari kelas" value="${kq}" data-kq></label>
        <div class="chip-row">${KF.map(([id, l]) => html`<button type="button" class="chip" data-kf="${id}">${l}</button>`)}</div>
        <span class="muted" data-kcount></span>
      </div>
      <div data-klist></div>`);
    if (!el.dataset.wired) {
      el.dataset.wired = '1';
      on(el, 'input', '[data-kq]', (e, inp) => { kq = inp.value; kn = 30; kelasPaint(el); });
      on(el, 'click', '[data-kf]', (e, b) => { kf = b.dataset.kf; kn = 30; kelasPaint(el); });
      on(el, 'click', '[data-kmore]', () => { kn += 30; kelasPaint(el); });
      on(el, 'click', '[data-open]', (e, b) => openClassSheet(b.dataset.open));
      on(el, 'click', '[data-edit]', (e, b) => openBookingSheet({ editId: b.dataset.edit, silent: true }));
      on(el, 'click', '[data-kadd]', () => openBookingSheet({ record: true, prefill: { date: isoDate(now()) },
        onDone: (b, x) => { if (b && x && x.markAttendance) openAttendanceSheet(b.id); } }));
      on(el, 'click', '[data-att]', (e, b) => openAttendanceSheet(b.dataset.att));
      on(el, 'click', '[data-kcancel]', (e, b) => startCancel(b.dataset.kcancel, { silent: true }));
      on(el, 'click', '[data-restore]', async (e, b) => { const r = await restoreBooking(b.dataset.restore); toast(r.ok ? 'Kelas dipulihkan' : r.message, r.ok ? 'success' : 'error'); });
    }
    kelasPaint(el);
  },
  update(reason) { if (reason === 'notifications' || reason === 'users' || reason === 'activity') return; const el = document.querySelector('[data-view="kelas"]'); if (el && el.querySelector('[data-klist]')) kelasPaint(el); }
};

/* ============================================================== Jadual Tetap */
function teacherSelect(subject, sel) {
  const ws = (state.config.workshopTeachers && state.config.workshopTeachers[subject]) || [];
  return html`<optgroup label="Guru subjek ini"><option value="primary"${sel === 'primary' ? ' selected' : ''}>${defaultTeacherFor(state.config, subject) || '—'}</option></optgroup>
    ${ws.length ? html`<optgroup label="Guru bengkel">${ws.map(n => html`<option value="${'workshop:' + n}">${n}</option>`)}</optgroup>` : ''}
    <optgroup label="Lain-lain"><option value="manual">Guru lain…</option></optgroup>`;
}
function tetapBoard(el) {
  const items = (state.config.recurringTemplates || []).slice().sort((a, b) => (WEEK_ORDER.indexOf(a.day) - WEEK_ORDER.indexOf(b.day)) || a.from.localeCompare(b.from));
  const n = now();
  setHTML(el.querySelector('[data-board]'), html`<div class="wboard">${WEEK_ORDER.map(d => {
    const list = items.filter(t => t.day === d);
    return html`<div class="wcol${d === ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'][n.getDay()] ? ' is-today' : ''}">
      <span class="wcol-h">${DAY_MY[d]}</span>
      ${list.length ? list.map(t => html`<div class="wcard" style="--c:${subjectColor(t.subject)}"><b>${subjectIcon(t.subject, 15)}${t.subject}</b><span>${t.from}–${t.to}</span><span class="muted">${t.teacher}</span>
        <button type="button" class="icon-btn wcard-x" data-rtdel="${t.id}" aria-label="Buang ${t.subject} ${DAY_MY[d]}">${icon('x', 15)}</button></div>`) : html`<span class="wcol-empty">—</span>`}
    </div>`;
  })}</div>${items.length ? '' : html`<p class="muted board-note">Belum ada jadual tetap. Tambah kelas yang berulang setiap minggu di atas.</p>`}`);
}
export const tetapView = {
  id: 'tetap',
  render(el) {
    const first = SUBJECTS[0].name;
    setHTML(el, html`
      <div class="page-head"><div><h2 class="page-title">Jadual tetap</h2><p class="page-sub">Kelas yang berulang setiap minggu. Kelas minggu semasa dijana secara automatik; minggu berikutnya muncul pada hari Ahad.</p></div>
        <span class="pill gold">${icon('key', 13)} Admin</span></div>
      <section class="tile rt-form">
        <form novalidate data-rtform>
          <div class="rt-grid">
            <label class="field"><span class="field-label">Subjek</span><select class="input" data-rt="subject">${SUBJECTS.map(s => html`<option value="${s.name}">${s.name}</option>`)}</select></label>
            <label class="field"><span class="field-label">Guru</span><select class="input" data-rt="teacher">${teacherSelect(first, 'primary')}</select></label>
            <label class="field" hidden data-rt-manual><span class="field-label">Nama guru</span><input class="input" type="text" autocomplete="off" placeholder="Contoh: Cikgu Ahmad" data-rt="manual"></label>
            <label class="field"><span class="field-label">Hari</span><select class="input" data-rt="day">${WEEK_ORDER.map(d => html`<option value="${d}">${DAY_MY[d]}</option>`)}</select></label>
            <label class="field"><span class="field-label">Mula</span><input class="input" type="time" step="300" value="14:30" data-rt="from"></label>
            <label class="field"><span class="field-label">Tamat</span><input class="input" type="time" step="300" value="16:00" data-rt="to"></label>
          </div>
          <p class="form-error" role="alert" hidden></p>
          <div class="form-actions"><button type="submit" class="btn primary">${icon('plus', 18)}<span>Tambah jadual tetap</span></button></div>
        </form>
      </section>
      <div class="section-label"><h3>Minggu tetap</h3><span class="muted">${(state.config.recurringTemplates || []).length} kelas setiap minggu</span></div>
      <section class="tile board-tile" data-board></section>`);
    tetapBoard(el);
    const $ = k => el.querySelector('[data-rt="' + k + '"]');
    $('subject').addEventListener('change', () => { setHTML($('teacher'), teacherSelect($('subject').value, 'primary')); el.querySelector('[data-rt-manual]').hidden = true; });
    $('teacher').addEventListener('change', () => { const m = el.querySelector('[data-rt-manual]'); m.hidden = $('teacher').value !== 'manual'; if (!m.hidden) $('manual').focus(); });
    el.querySelector('[data-rtform]').addEventListener('submit', async e => {
      e.preventDefault();
      const err = el.querySelector('.rt-form .form-error');
      err.hidden = true;
      const subject = $('subject').value, sel = $('teacher').value;
      const teacher = sel === 'primary' ? defaultTeacherFor(state.config, subject) : sel === 'manual' ? $('manual').value.trim() : sel.slice(9);
      if (!teacher) { err.textContent = sel === 'manual' ? 'Tulis nama guru.' : 'Subjek ini belum ada guru utama.'; err.hidden = false; return; }
      const r = await addTemplate({ subject, teacher, day: $('day').value, from: $('from').value, to: $('to').value });
      if (!r.ok) { err.textContent = r.message; err.hidden = false; return; }
      toast(subject + ' ditambah: setiap ' + DAY_MY[$('day').value] + ', ' + $('from').value, 'success');
    });
    if (!el.dataset.wired) {
      el.dataset.wired = '1';
      on(el, 'click', '[data-rtdel]', async (e, b) => {
        const t = (state.config.recurringTemplates || []).find(x => x.id === b.dataset.rtdel);
        if (!t) return;
        if (!(await confirmDialog({ title: 'Buang jadual tetap?', message: t.subject + ' setiap ' + DAY_MY[t.day] + ', ' + t.from + '–' + t.to + '. Kelas yang sudah dijana kekal dalam jadual.', confirmLabel: 'Buang', tone: 'danger' }))) return;
        const r = await removeTemplate(t.id);
        toast(r.ok ? 'Jadual tetap dibuang' : r.message, r.ok ? 'info' : 'error');
      });
    }
  },
  update(reason) { if (reason !== 'config') return; const el = document.querySelector('[data-view="tetap"]'); if (el && el.querySelector('[data-board]')) { tetapBoard(el); const lab = el.querySelector('.section-label .muted'); if (lab) lab.textContent = (state.config.recurringTemplates || []).length + ' kelas setiap minggu'; } }
};

/* ======================================================================== Data */
function sourceText(info) {
  if (info.source === 'demo') return { title: 'Data demo', sub: 'Contoh 10 minggu yang dijana, dengan kelas sedang berlangsung.' };
  if (info.source === 'import') return { title: 'Sandaran yang diimport', sub: 'Dipulihkan daripada fail .json.' };
  return { title: 'Data sebenar', sub: 'Laman asal 5 Sigma, disalin ' + (info.takenAt ? dateShort(isoDate(new Date(info.takenAt))) + ' ' + new Date(info.takenAt).getFullYear() : '5 Okt 2026') + '.' };
}
function sandboxHTML() {
  const n = now(), off = getOffset();
  const info = dataInfo();
  const src = sourceText(info);
  return html`<div class="sbx">
    <div class="sbx-src">
      <span class="field-label">Sumber data</span>
      <div class="choice-grid">
        <button type="button" class="choice${info.source === 'real' ? ' is-on' : ''}" data-src="real" aria-pressed="${info.source === 'real' ? 'true' : 'false'}"><b>${icon('database', 16)} Data sebenar</b><span>Tempahan, kehadiran dan log dari laman asal (disalin 5 Okt 2026).</span></button>
        <button type="button" class="choice${info.source === 'demo' ? ' is-on' : ''}" data-src="demo" aria-pressed="${info.source === 'demo' ? 'true' : 'false'}"><b>${icon('spark', 16)} Data demo</b><span>Contoh 10 minggu, ada kelas sedang berlangsung. Untuk mencuba semua fungsi.</span></button>
      </div>
      <p class="muted sbx-note">Sedang digunakan: <b>${src.title}</b>. ${src.sub} Perubahan disimpan dalam pelayar ini sahaja dan tidak dihantar ke laman asal.</p>
    </div>
    <p class="sbx-state"><span class="pill ${state.persistent ? 'st-ongoing' : 'st-extending'}">${state.persistent ? 'Disimpan dalam pelayar ini' : 'Mod memori'}</span>
      <span class="muted">${state.persistent ? 'Data kekal selepas muat semula. Tab lain dalam pelayar yang sama dikemas kini serta-merta.' : 'Storan pelayar disekat di sini: data hilang apabila halaman ditutup.'}</span></p>
    <div class="sbx-clock"><div><span class="field-label">Jam aplikasi</span><b data-sbx-time>${dateLong(isoDate(n))}, ${pad2(n.getHours())}:${pad2(n.getMinutes())}</b>
      <span class="muted">${off ? 'Dianjak ' + (off > 0 ? '+' : '−') + Math.round(Math.abs(off) / 60000) + ' minit daripada masa sebenar' : 'Masa sebenar'}</span></div>
      <div class="chip-row"><button type="button" class="chip" data-jump="next">${icon('play', 14)} Lompat ke kelas seterusnya</button><button type="button" class="chip" data-jump="60">+1 jam</button><button type="button" class="chip" data-jump="1440">+1 hari</button>${off ? html`<button type="button" class="chip is-on" data-jump="0">${icon('undo', 14)} Masa sebenar</button>` : ''}</div></div>
    <div class="sbx-actions">
      <button type="button" class="btn ghost" data-sbx="export">${icon('download', 16)}<span>Eksport sandaran (.json)</span></button>
      <label class="btn ghost sbx-file">${icon('upload', 16)}<span>Import sandaran</span><input type="file" accept="application/json,.json" data-sbx-import></label>
      <button type="button" class="btn ghost danger-text" data-sbx="reset">${icon('undo', 16)}<span>Set semula ${info.source === 'demo' ? 'data demo' : 'ke data sebenar'}</span></button>
    </div>
  </div>`;
}
function wireSandbox(root, after) {
  on(root, 'click', '[data-src]', async (e, b) => {
    const to = b.dataset.src, info = dataInfo();
    if (to === info.source) return;
    const ok = await confirmDialog({
      title: to === 'demo' ? 'Tukar ke data demo?' : 'Kembali ke data sebenar?',
      message: to === 'demo' ? 'Data dalam pelayar ini diganti dengan contoh 10 minggu yang dijana. Anda boleh kembali ke data sebenar bila-bila masa.' : 'Data dalam pelayar ini diganti dengan salinan data laman asal (5 Okt 2026). Perubahan yang dibuat di sini akan hilang.',
      confirmLabel: to === 'demo' ? 'Guna data demo' : 'Guna data sebenar'
    });
    if (!ok) return;
    setDataSource(to);
    refreshNow();
    toast(to === 'demo' ? 'Data demo digunakan' : 'Data sebenar dipulihkan', 'success');
    if (after) after();
  });
  on(root, 'click', '[data-jump]', (e, b) => {
    const v = b.dataset.jump;
    if (v === '0') setOffset(0);
    else if (v === 'next') {
      const nx = sortByTime(state.bookings.filter(x => !x.cancelledAt && computeStatus(x, now()) === 'upcoming'))[0];
      if (!nx) { toast('Tiada kelas akan datang untuk dilompat. Tempah satu, atau guna data demo.', 'info'); return; }
      setOffset(getOffset() + (at(nx.date, nx.from).getTime() + 5 * 60000 - now().getTime()));
      toast('Jam aplikasi: 5 minit selepas ' + nx.subject + ' bermula', 'info');
    } else setOffset(getOffset() + (+v) * 60000);
    refreshNow();
    if (after) after();
  });
  on(root, 'click', '[data-sbx]', async (e, b) => {
    if (b.dataset.sbx === 'export') {
      const r = await saveFile('sandaran-5sigma-' + isoDate(now()) + '.json', exportBackup(), 'application/json');
      if (r.ok) toast('Sandaran disimpan', 'success'); else toast(r.message, 'error');
    } else if (b.dataset.sbx === 'reset') {
      const demo = dataInfo().source === 'demo';
      if (!(await confirmDialog({ title: demo ? 'Set semula data demo?' : 'Set semula ke data sebenar?', message: 'Semua tempahan, kehadiran dan perubahan dalam pelayar ini kembali kepada ' + (demo ? 'data demo asal.' : 'salinan data laman asal (5 Okt 2026).'), confirmLabel: 'Set semula', tone: 'danger' }))) return;
      setOffset(0); resetDemo(); refreshNow(); toast(demo ? 'Data demo dijana semula' : 'Data sebenar dipulihkan', 'success');
      if (after) after();
    }
  });
  on(root, 'change', '[data-sbx-import]', (e, inp) => {
    const f = inp.files && inp.files[0];
    if (!f) return;
    const rd = new FileReader();
    rd.onload = () => { const r = importBackup(String(rd.result || '')); toast(r.ok ? 'Sandaran dipulihkan' : r.message, r.ok ? 'success' : 'error'); inp.value = ''; if (after) after(); };
    rd.readAsText(f);
  });
}
export function openSandboxSheet() {
  if (!state.isAdmin) return;
  const s = openSheet({ title: 'Data', sub: 'Aplikasi ini berjalan dalam pelayar anda, dengan model data yang sama seperti Firestore laman asal.', cls: 'is-dialog sheet-sbx', keepFocus: true, content: sandboxHTML() });
  wireSandbox(s.body, () => s.setContent(sandboxHTML()));
}

/* ==================================================================== Tetapan */
function tetapanPaint(el) {
  const teachers = allKnownTeachers(state.config, state.bookings);
  const ws = [];
  Object.keys(state.config.workshopTeachers || {}).forEach(sub => (state.config.workshopTeachers[sub] || []).forEach(nm => ws.push({ sub, nm })));
  const canNotify = !onClaude && 'Notification' in window;
  setHTML(el, html`
    <div class="page-head"><div><h2 class="page-title">Tetapan</h2><p class="page-sub">${state.isAdmin ? 'Paparan, guru subjek, guru bengkel dan data.' : 'Paparan, guru subjek dan guru bengkel.'}</p></div></div>
    <div class="set-grid">
      <section class="tile set-card"><h3>${icon('moon', 18)} Paparan</h3>
        <div class="set-row"><div><b>Tema</b><span>Malam ialah rupa asal Langit 5Σ. Subuh lebih cerah untuk siang hari.</span></div>
          <div class="seg seg-lg"><button type="button" data-theme-set="dark" class="${getTheme() === 'dark' ? 'is-on' : ''}">${icon('moon', 15)}<span>Malam</span></button><button type="button" data-theme-set="light" class="${getTheme() === 'light' ? 'is-on' : ''}">${icon('sun', 15)}<span>Subuh</span></button></div></div>
        <div class="set-row"><div><b>Kurangkan animasi</b><span>Langit menjadi pegun dan peralihan dipendekkan.</span></div>
          <button type="button" class="switch${motionReduced() ? ' is-on' : ''}" role="switch" aria-checked="${motionReduced() ? 'true' : 'false'}" data-motion aria-label="Kurangkan animasi"><i></i></button></div>
        ${canNotify ? html`<div class="set-row"><div><b>Notifikasi peranti</b><span>${Notification.permission === 'granted' ? 'Dibenarkan. Anda akan dimaklumkan walaupun tab tersembunyi.' : Notification.permission === 'denied' ? 'Disekat dalam tetapan pelayar.' : 'Terima makluman kelas baharu dan perubahan di peranti ini.'}</span></div>
          ${Notification.permission === 'default' ? html`<button type="button" class="btn ghost sm" data-notify>${icon('bell', 15)}<span>Benarkan</span></button>` : html`<span class="pill ${Notification.permission === 'granted' ? 'st-ongoing' : ''}">${Notification.permission === 'granted' ? 'Aktif' : 'Disekat'}</span>`}</div>` : ''}
      </section>
      <section class="tile set-card set-wide"><h3>${icon('subjek', 18)} Guru utama setiap subjek</h3>
        <div class="set-list">${SUBJECTS.map(s => html`<div class="set-row compact"><div class="set-subj">${subjectBadge(s.name, 'sm')}<div><b>${s.name}</b><span>${defaultTeacherFor(state.config, s.name) || 'Belum ditetapkan'}</span></div></div>
          <button type="button" class="btn ghost sm" data-subject-edit="${s.name}">${icon('kelas', 15)}<span>Tukar</span></button></div>`)}</div>
      </section>
      <section class="tile set-card"><h3>${icon('guru', 18)} Jantina guru</h3>
        <p class="muted set-note">Digunakan untuk sapaan yang betul.</p>
        <div class="set-list">${teachers.length ? teachers.map(t => { const g = state.config.teacherGenders[t]; return html`<div class="set-row compact"><div><b>${t}</b></div>
          <div class="seg"><button type="button" class="${g === 'M' ? 'is-on t-info' : ''}" data-gender="${t}" data-g="M" aria-pressed="${g === 'M' ? 'true' : 'false'}">L</button><button type="button" class="${g === 'F' ? 'is-on t-info' : ''}" data-gender="${t}" data-g="F" aria-pressed="${g === 'F' ? 'true' : 'false'}">P</button></div></div>`; }) : html`<p class="muted">Tiada guru lagi.</p>`}</div>
      </section>
      <section class="tile set-card"><h3>${icon('tetapan', 18)} Guru bengkel</h3>
        <p class="muted set-note">Guru tambahan untuk subjek tertentu, boleh dipilih semasa menempah.</p>
        <div class="ws-chips">${ws.length ? ws.map(w => html`<span class="ws-chip" style="--c:${subjectColor(w.sub)}"><i class="dot"></i>${w.sub}: <b>${w.nm}</b><button type="button" data-ws-del="${w.sub}|${w.nm}" aria-label="Buang ${w.nm}">${icon('x', 13)}</button></span>`) : html`<p class="muted">Belum ada guru bengkel.</p>`}</div>
        <form class="ws-form" novalidate data-ws-form>
          <select class="input" data-ws-subject aria-label="Subjek">${SUBJECTS.map(s => html`<option value="${s.name}">${s.name}</option>`)}</select>
          <input class="input" type="text" autocomplete="off" placeholder="Nama guru bengkel" aria-label="Nama guru bengkel" data-ws-name>
          <button type="submit" class="btn primary">${icon('plus', 16)}<span>Tambah</span></button>
        </form>
      </section>
      ${state.isAdmin ? html`<section class="tile set-card set-wide"><h3>${icon('database', 18)} Data <span class="pill">Admin</span></h3><div data-sbx-host>${sandboxHTML()}</div></section>` : ''}
      <section class="tile set-card set-wide about"><h3>${icon('info', 18)} Tentang</h3>
        <p><b>5 Sigma Class Hub</b> ${APP_VERSION} · Langit 5Σ. Dibina dengan HTML, CSS dan JavaScript tulen (ES modules), tanpa pustaka luar.</p>
        <p class="muted">Fon: TeX Gyre Adventor (GUST Font License) dan Inter (SIL Open Font License 1.1). Jadual SPM 2026: Lembaga Peperiksaan, KPM (18 Ogos 2026). Data sebenar: laman asal Jadual Booking Kelas 5 Sigma.</p>
        <div class="kbd-list"><span><kbd>Ctrl</kbd> + <kbd>K</kbd> Tanya Sigma</span><span><kbd>Alt</kbd> + <kbd>←</kbd>/<kbd>→</kbd> minggu sebelum/seterusnya dalam Jadual</span><span><kbd>Esc</kbd> tutup panel</span></div>
      </section>
    </div>`);
}
export const tetapanView = {
  id: 'tetapan',
  render(el) {
    tetapanPaint(el);
    if (el.dataset.wired) return;
    el.dataset.wired = '1';
    on(el, 'click', '[data-theme-set]', (e, b) => { setTheme(b.dataset.themeSet, b); setTimeout(() => tetapanPaint(el), 80); });
    on(el, 'click', '[data-motion]', () => { setReducedMotion(!motionReduced()); tetapanPaint(el); });
    on(el, 'click', '[data-notify]', async () => { try { const p = await Notification.requestPermission(); toast(p === 'granted' ? 'Notifikasi peranti diaktifkan' : 'Notifikasi peranti tidak dibenarkan', p === 'granted' ? 'success' : 'info'); } catch (err) { /* ignore */ } tetapanPaint(el); });
    on(el, 'click', '[data-subject-edit]', async (e, b) => {
      const sub = b.dataset.subjectEdit;
      const v = await promptDialog({ title: 'Guru utama ' + sub, label: 'Nama guru', value: defaultTeacherFor(state.config, sub) || '', placeholder: 'Contoh: Cikgu Rahim' });
      if (v == null) return;
      const r = await setSubjectTeacher(sub, v);
      toast(r.ok ? 'Guru utama ' + sub + ': ' + v.trim() : r.message, r.ok ? 'success' : 'error');
    });
    on(el, 'click', '[data-gender]', async (e, b) => { const r = await setTeacherGender(b.dataset.gender, b.dataset.g); if (!r.ok) toast(r.message, 'error'); });
    on(el, 'click', '[data-ws-del]', async (e, b) => { const [sub, nm] = b.dataset.wsDel.split('|'); const r = await removeWorkshopTeacher(sub, nm); toast(r.ok ? nm + ' dibuang' : r.message, r.ok ? 'info' : 'error'); });
    on(el, 'submit', '[data-ws-form]', async e => {
      e.preventDefault();
      const sub = el.querySelector('[data-ws-subject]').value, nm = el.querySelector('[data-ws-name]').value;
      const r = await addWorkshopTeacher(sub, nm);
      toast(r.ok ? 'Guru bengkel ditambah untuk ' + sub : r.message, r.ok ? 'success' : 'error');
    });
    wireSandbox(el, () => { const h = el.querySelector('[data-sbx-host]'); if (h) setHTML(h, sandboxHTML()); });
  },
  update(reason) {
    if (reason !== 'config' && reason !== 'bookings') return;
    const el = document.querySelector('[data-view="tetapan"]');
    if (!el || (el.contains(document.activeElement) && document.activeElement.matches('input, select'))) return;
    const y = window.scrollY; tetapanPaint(el); window.scrollTo(0, y);
  }
};
